name: Hello World on Self-Hosted Runner

on:
  push:
    branches:
      - TestSelfHostedRunner

jobs:
  say-hello:
    runs-on: self-hosted  # Use the self-hosted runner
    steps:
      - name: Print Hello World
        run: echo "Hello World!"
